name: Daily Weather Bot
# run-name: 
on: 
  push:
  
jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run App
        run: python app.py


      
